version: "3.8"

volumes:
  mysql_data:

services:
  api:
    build: .
    env_file:
      - ./.env
    # environment:
    #   HOST: 0.0.0.0
    #   PORT: 3000
    #   DB_USER: root
    #   DB_PASS: 123456
    #   DB_HOST: mysql
    #   DB_PORT: 3306
    #   DB_NAME: courses
    ports:
      - 3000:3000

  mysql:
    image: mysql:8.0.22
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/migration:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: courses
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: 123456
